version: '2'

services:
  consul:
    image: consul:0.8.3
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net
  simple-server:
    build:
      context:
      dockerfile: server/Dockerfile
    image: simple-server:1.0.1
    environment:
      - CONSUL_ADDR:consul:8500
    depends_on:
      - consul
    networks:
      - sky-net

networks:
  sku-net:
    driver: bridge
